package ryannewsom.application;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;
import ryannewsom.model.appointment.Appointment;
import ryannewsom.model.users.User;

import java.util.List;

/**
 * Mongo Repository interface. The implementation is generated by Spring out of the interface via dependency injection.
 * Spring's Data project handles this. Basically extracting the complexities of the database queries from the
 * developer. MongoRepository extends CrudRepository which is the base interface for CRUD with a database.
 * I used MongoRepository to allow for direct db implementation functionality.
 */
@Repository
public interface AppointmentRepository extends MongoRepository<Appointment, String> {
    public List<Appointment> findByUser(User user);
}
